import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  ca: {
    // Home
    'parvosHub': 'Parvos Hub',
    'homeSubtitle': 'Control intel·ligent de despeses familiars',
    'registro': 'Registre de Despeses',
    'registroDesc': 'Controla i registra totes les despeses',
    'resumen': 'Resum Anual',
    'resumenDesc': 'Anàlisi detallat de despeses',
    'presupuestos': 'Pressupostos',
    'proximamente': 'Pròximament',
    'resumenDelAno': 'Resum de l\'Any',
    'volver': 'Tornar',
    'calendarioGastos': 'Calendari de Despeses',
    'sinEventosEstesMes': 'Cap evento aquest mes',
    
    // Meses
    'enero': 'Gener',
    'febrero': 'Febrer',
    'marzo': 'Març',
    'abril': 'Abril',
    'mayo': 'Maig',
    'junio': 'Juny',
    'julio': 'Juliol',
    'agosto': 'Agost',
    'septiembre': 'Setembre',
    'octubre': 'Octubre',
    'noviembre': 'Novembre',
    'diciembre': 'Desembre',
    
    // Categorías
    'vacaciones': 'Vacacions',
    'ocio': 'Oci',
    'hogar': 'Llar',
    'movilidad': 'Mobilitat',
    'deporte': 'Esport',
    'extra': 'Extra',
    'alimentacion': 'Alimentació',
    'ingreso': 'Ingreso',
    'gasto': 'Despesa',
    'hucha': 'Estalvi',
    'retiradahucha': 'Retirada Estalvi',
    
    // ExpenseTracker
    'fecha': 'Data',
    'tipo': 'Tipus',
    'cantidad': 'Quantitat',
    'descripcion': 'Descripció o informació (opcional)',
    'categoria': 'Categoria',
    'usuario': 'Usuari',
    'cuenta': 'Compte',
    'anadir': 'Afegir',
    'guardarCambios': 'Guardar canvis',
    'cancelar': 'Cancel·lar',
    'situacionGlobal': '💰 SITUACIÓ GLOBAL',
    'ingresos': 'Ingressos',
    'gastos': 'Despeses',
    'huchaTotal': 'Estalvi Total',
    'saldoActual': 'Saldo actual',
    'movimiento': 'Moviment',
    'editando': '✏️ Editant moviment',
    'seguro': '¿Estàs segur que vols borrar aquest moviment?',
    'borrado': 'Moviment esborrat.',
    'error': 'Error en guardar la operació.',
    'exito': 'Operació afegida correctament.',
    'actualizacion': 'Operació actualitzada correctament.',
    'selectCategoria': 'Selecciona categoria',
    'selectUsuario': 'Selecciona usuari',
    'selectCuenta': 'Selecciona compte',
    'camposObligatorios': 'Per favor, completa tots els camps obligatoris.',
    'errorBorrar': 'Error en borrar el moviment',
    'registroDeGastos': 'Registre de Despeses',
    'resumenAnual': 'Resum Anual',
    'calendario': 'Calendari',
    'receteario': 'Receptari',
    'listaCompra': 'Llista de Compra',
    'noPresupuestosGuardados': 'No hay presupuestos guardados para este mes aún',
    'errorCargarOperaciones': 'Error en cargar operaciones',
    'presupuestosDelMes': 'Pressupostos del Mes',
    'ahorroDelMes': 'Estalvi del Mes',
    'tabla': 'Taula',
    'resumenMensual': 'Resum Mensual',
    'ultimosMovimientos': 'Últims Moviments',
    'filtros': 'Filtres',
    'allCategories': 'Totes les categories',
    'allAccounts': 'Tots els comptes',
    'itemsPerPage': 'Elements per pàgina',
    
    // Botones y acciones
    'anterior': 'Anterior',
    'siguiente': 'Següent',
    'volver': 'Tornar',
    'verTodos': 'Veure Tots',
    'nuevoEvento': 'Nou Evento',
    'editarEvento': 'Editar Evento',
    'verMes': 'Veure Mes',
    'verAno': 'Veure Any',
    'nuevoMovimiento': '+ Nou evento',
    'editar': 'Editar',
    'guardar': 'Guardar',
    'borrar': 'Borrar',
  },
  gl: {
    // Home
    'parvosHub': 'Parvos Hub',
    'homeSubtitle': 'Control intelixente de gastos familiares',
    'registro': 'Rexistro de Gastos',
    'registroDesc': 'Controla e registra todos os gastos',
    'resumen': 'Resumo Anual',
    'resumenDesc': 'Análise detallada de gastos',
    'presupuestos': 'Orzamentos',
    'proximamente': 'Proximamente',
    'resumenDelAno': 'Resumo do Ano',
    'volver': 'Voltar',
    'calendarioGastos': 'Calendario de Gastos',
    'sinEventosEstesMes': 'Ningún evento este mes',
    
    // Meses
    'enero': 'Xaneiro',
    'febrero': 'Febreiro',
    'marzo': 'Marzo',
    'abril': 'Abril',
    'mayo': 'Maio',
    'junio': 'Xuño',
    'julio': 'Xullo',
    'agosto': 'Agosto',
    'septiembre': 'Setembro',
    'octubre': 'Outubro',
    'noviembre': 'Novembro',
    'diciembre': 'Decembro',
    
    // Categorías
    'vacaciones': 'Vacacións',
    'ocio': 'Ocio',
    'hogar': 'Fogar',
    'movilidad': 'Mobilidade',
    'deporte': 'Deporte',
    'extra': 'Extra',
    'alimentacion': 'Alimentación',
    'ingreso': 'Ingreso',
    'gasto': 'Gasto',
    'hucha': 'Aforro',
    'retiradahucha': 'Retirada Aforro',
    
    // ExpenseTracker
    'fecha': 'Data',
    'tipo': 'Tipo',
    'cantidad': 'Cantidade',
    'descripcion': 'Descripción ou información (opcional)',
    'categoria': 'Categoría',
    'usuario': 'Usuario',
    'cuenta': 'Conta',
    'anadir': 'Engadir',
    'guardarCambios': 'Gardar cambios',
    'cancelar': 'Cancelar',
    'situacionGlobal': '💰 SITUACIÓN GLOBAL',
    'ingresos': 'Ingresos',
    'gastos': 'Gastos',
    'huchaTotal': 'Aforro Total',
    'saldoActual': 'Saldo actual',
    'movimiento': 'Movemento',
    'editando': '✏️ Editando movemento',
    'seguro': '¿Estás seguro de que queres borrar este movemento?',
    'borrado': 'Movemento borrado.',
    'error': 'Erro ao gardar a operación.',
    'exito': 'Operación engadida correctamente.',
    'actualizacion': 'Operación actualizada correctamente.',
    'selectCategoria': 'Selecciona categoría',
    'selectUsuario': 'Selecciona usuario',
    'selectCuenta': 'Selecciona conta',
    'camposObligatorios': 'Por favor, completa todos os campos obrigatorios.',
    'errorBorrar': 'Erro ao borrar o movemento',
    'registroDeGastos': 'Rexistro de Gastos',
    'resumenAnual': 'Resumo Anual',
    'calendario': 'Calendario',
    'receteario': 'Recetario',
    'listaCompra': 'Lista de Compra',
    'noPresupuestosGuardados': 'No hai orzamentos gardados para este mes aínda',
    'errorCargarOperaciones': 'Erro ao cargar operacións',
    'presupuestosDelMes': 'Orzamentos do Mes',
    'ahorroDelMes': 'Aforro do Mes',
    'tabla': 'Táboa',
    'resumenMensual': 'Resumo Mensual',
    'ultimosMovimientos': 'Últimos Movementos',
    'filtros': 'Filtros',
    'allCategories': 'Todas as categorías',
    'allAccounts': 'Todas as contas',
    'itemsPerPage': 'Elementos por páxina',
    
    // Botones y acciones
    'anterior': 'Anterior',
    'siguiente': 'Seguinte',
    'volver': 'Volver',
    'verTodos': 'Ver Todos',
    'nuevoEvento': 'Novo Evento',
    'editarEvento': 'Editar Evento',
    'verMes': 'Ver Mes',
    'verAno': 'Ver Ano',
    'nuevoMovimiento': '+ Novo evento',
    'editar': 'Editar',
    'guardar': 'Guardar',
    'borrar': 'Borrar',
  },
  es: {
    // Home
    'parvosHub': 'Parvos Hub',
    'homeSubtitle': 'Control inteligente de gastos familiares',
    'registro': 'Registro de Gastos',
    'registroDesc': 'Controla y registra todos los gastos',
    'resumen': 'Resumen Anual',
    'resumenDesc': 'Análisis detallado de gastos',
    'presupuestos': 'Presupuestos',
    'resumenDelAno': 'Resumen del Año',
    'volver': 'Volver',
    'calendarioGastos': 'Calendario de Gastos',
    'sinEventosEstesMes': 'Ningún evento este mes',
    
    // Meses
    'enero': 'Enero',
    'febrero': 'Febrero',
    'marzo': 'Marzo',
    'abril': 'Abril',
    'mayo': 'Mayo',
    'junio': 'Junio',
    'julio': 'Julio',
    'agosto': 'Agosto',
    'septiembre': 'Septiembre',
    'octubre': 'Octubre',
    'noviembre': 'Noviembre',
    'diciembre': 'Diciembre',
    
    // Categorías
    'vacaciones': 'Vacaciones',
    'ocio': 'Ocio',
    'hogar': 'Hogar',
    'movilidad': 'Movilidad',
    'deporte': 'Deporte',
    'extra': 'Extra',
    'alimentacion': 'Alimentación',
    'ingreso': 'Ingreso',
    'gasto': 'Gasto',
    'hucha': 'Hucha',
    'retiradahucha': 'Retirada Hucha',
    
    // ExpenseTracker
    'fecha': 'Fecha',
    'tipo': 'Tipo',
    'cantidad': 'Cantidad',
    'descripcion': 'Descripción o información (opcional)',
    'categoria': 'Categoría',
    'usuario': 'Usuario',
    'cuenta': 'Cuenta',
    'anadir': 'Añadir',
    'guardarCambios': 'Guardar cambios',
    'cancelar': 'Cancelar',
    'situacionGlobal': '💰 SITUACIÓN GLOBAL',
    'ingresos': 'Ingresos',
    'gastos': 'Gastos',
    'huchaTotal': 'Hucha Total',
    'saldoActual': 'Saldo actual',
    'movimiento': 'Movimiento',
    'editando': '✏️ Editando movimiento',
    'seguro': '¿Estás seguro de que quieres borrar este movimiento?',
    'borrado': 'Movimiento borrado.',
    'error': 'Error al guardar la operación.',
    'exito': 'Operación añadida correctamente.',
    'actualizacion': 'Operación actualizada correctamente.',
    'selectCategoria': 'Selecciona categoría',
    'selectUsuario': 'Selecciona usuario',
    'selectCuenta': 'Selecciona cuenta',
    'camposObligatorios': 'Por favor, completa todos los campos obligatorios.',
    'errorBorrar': 'Error al borrar el movimiento',
    'registroDeGastos': 'Registro de Gastos',
    'resumenAnual': 'Resumen Anual',
    'calendario': 'Calendario',
    'receteario': 'Recetario',
    'listaCompra': 'Lista de Compra',
    'noPresupuestosGuardados': 'No hay presupuestos guardados para este mes aún',
    'errorCargarOperaciones': 'Error al cargar operaciones',
    'presupuestosDelMes': 'Presupuestos del Mes',
    'ahorroDelMes': 'Ahorro del Mes',
    'tabla': 'Tabla',
    'resumenMensual': 'Resumen Mensual',
    'ultimosMovimientos': 'Últimos Movimientos',
    'filtros': 'Filtros',
    'allCategories': 'Todas las categorías',
    'allAccounts': 'Todas las cuentas',
    'itemsPerPage': 'Elementos por página',
    
    // Botones y acciones
    'anterior': 'Anterior',
    'siguiente': 'Siguiente',
    'volver': 'Volver',
    'verTodos': 'Ver Todos',
    'nuevoEvento': 'Nuevo Evento',
    'editarEvento': 'Editar Evento',
    'verMes': 'Ver Mes',
    'verAno': 'Ver Año',
    'nuevoMovimiento': '+ Nuevo evento',
    'editar': 'Editar',
    'guardar': 'Guardar',
    'borrar': 'Borrar',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('ca');

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, t, changeLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage debe ser usado dentro de LanguageProvider');
  }
  return context;
};
